# config for the `create` command
create:
  sde:
    # connection string to the sde database
    db: oraclesde://sde:password@gis__tns
  users:
    # include users that contain any of these strings
    include:
      - GIS_
    # exclude users that contain any of these strings
    exclude:
      - GIS_ACS

# config for the `get_changes` command
get_changes:
  logging:
    version: 1
    formatters:
      basic:
        format: '%(asctime)s %(message)s'
      json:
        (): 'pythonjsonlogger.jsonlogger.JsonFormatter'
        format: '(inventory_time) (change_type) (change_data)'
    handlers:
      file:
        class : logging.handlers.RotatingFileHandler
        formatter: json
        filename: changes.log
        maxBytes: 1024
        backupCount: 0
    root:
      level: INFO
      handlers: [file]
